- name: "mysql install"
  yum: name={{ item }} state=installed
  with_items:
    - mysql56
    - mysql56-server

- name: "is sysconfig network exists"
  stat: path=/etc/sysconfig/network
  register: is_sysconfig_network

- name: "set sysconfig network"
  shell: echo NETWORKING=yes > /etc/sysconfig/network
  when: not is_sysconfig_network.stat.exists

- name: "setup mysqld"
  service: name=mysqld state=started

- name: "add mysqld to chkconfig"
  service: name=mysqld enabled=yes
